### PR TITLE
ci: include macos + windows

### PR DESCRIPTION
**Pull request by hinto-janai**
Installs `boost` on macOS + Windows and adds them back to CI.

To be fixed:
- `monerod` only spawned on Linux https://github.com/hinto-janai/cuprate/actions/runs/7808923461/job/21299883505
- Windows error from https://github.com/Cuprate/cuprate/pull/50 (https://github.com/hinto-janai/cuprate/actions/runs/7808733161/job/21299591221)

### CODE REVIEW

**Comment by SyntheticBird45** [comment]
Pardon my indulgence, but why do we need `boost` ?

**Comment by hinto-janai** [comment]
I'm not sure, it was added in https://github.com/Cuprate/cuprate/pull/33. It seems to only be used here: https://github.com/Cuprate/cuprate/blob/1f677562eb753d07e2d035f0690a22e096140aae/cryptonight/c/warnings.h#L14

**Comment by hinto-janai** [comment]
I think this PR works, but it's stuck on `cryptonight/` using `#include <unistd.h>` in some places which doesn't exist on Windows.

`cryptonight/build.rs` needs whatever workarounds Monero's CMake files use.

**Comment by Boog900** [comment]
On windows Monero uses MSYS2 as a build environment: https://github.com/monero-project/monero?tab=readme-ov-file#on-windows

I think that provides `unistd.h` right? 

I don't know how easy it will be to work around that.

**Comment by SyntheticBird45** [comment]
Compiles fine with `msys2-runtime-devel` package installed

**Comment by Boog900** [comment]
Good news cryptonight-cuprate builds, bad news RandomX does not.

**Comment by Boog900** [comment]
I think this is going to require adding `windows-gnu` support to randomX or adding `windows-msvc` to cryptonight-cuprate.

**Comment by SyntheticBird45** [comment]
> I think this is going to require adding windows-gnu support to randomX* or adding windows-msvc to cryptonight-cuprate.

Take whatever is less work. For such algorithms that doesn't require specific platform API, you can take whatever you want. I think gnu is the way to go since some people on stackoverflow said it generated better quality code. Now if it is more easy to edit cryptonight ig we can go to msvc

**Comment by Boog900** [comment]
Ok building works but we can't reach monerod on windows....

**Comment by Boog900** [comment]
Ok it all works now.

When running tests Cuprate will now look in the `target` folder for monerod if it's not there it will download it, then it will spawn it with the flags specified.

@hinto-janai is there anything else you want to add or can I merge

**Comment by hinto-janai** [comment]
Thanks for this, it did not look fun...

Can you add documentation explaining `test-utils/`? A small 1 line README is ok, I can fill it in eventually.

**Comment by Boog900** [comment]
@hinto-janai done :)

**Comment by hinto-janai** [comment]
OK for merge.

**Pull request merged**
