### PR TITLE
ci: downgrade to `gcc 13.2` for windows

### PR DESCRIPTION
**Pull request by hinto-janai**
Will fix issue in https://github.com/Cuprate/cuprate/pull/65, https://github.com/Cuprate/cuprate/pull/126.

### CODE REVIEW

**Comment by hinto-janai** [comment]
@Boog900 no idea what's going on here, I'm going to setup a VM and debug there - will take a bit, sorry.

**Comment by Boog900** [comment]
Alright thanks, we updated both Rust and `lmdb-master-sys` recently, might be worth rolling them back and seeing if it fixes this?

**Comment by Boog900** [comment]
I think this might be because of gcc 14, it seems that recently landed in msys2 repos, we could try downgrade it

**Comment by hinto-janai** [comment]
Yup, was going to say the same, not sure if msys2 repos allow downgrading though.

Is `cryptonight/` the only thing preventing us from using MSVC?

**Comment by Boog900** [comment]
yeah I think so

**Review by Boog900 — APPROVED** [review]
Thanks for fixing this

**Pull request merged**
