### PR TITLE
ci: fix windows/macos

### PR DESCRIPTION
**Pull request by hinto-janai**
Fixes https://github.com/Cuprate/cuprate/actions/runs/8837940450/job/24268522093.

### CODE REVIEW

**Comment by hinto-janai** [comment]
@Boog900

1. There is no `cargo` or `rustup` binary in the `macos-latest` CI cache for some reason, seems like it was deleted, then the empty folder got saved somehow?
2. [`boost` headers can't be found](https://github.com/Cuprate/cuprate/actions/runs/8840794411/job/24276749998?pr=116) on macOS anymore

1 can be temporary fixed by clearing cache (let me know when you have so I can add it back).

2 is fixed by manually including Homebrew's lib path in the `build.rs`.

**Comment by Boog900** [comment]
I cleared the macOS cache

**Comment by hinto-janai** [comment]
2 more issues/fixes:

- Our macOS CI switched to `aarch64`: https://github.com/Cuprate/cuprate/actions/runs/8854593567/job/24317944403#step:9:553; added a `monerod` downloader for it
- Windows cryptonight build fails: https://github.com/Cuprate/cuprate/actions/runs/8854813110/job/24318620815?pr=116#step:7:2277; put back the line I removed [here](https://github.com/Cuprate/cuprate/commit/8f22d8ab79ebedee7213a829d4ffc37faf89db61#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fL103-L105), I think the reason it worked without it was because it was in our cache

**Review by Boog900 — APPROVED** [review]
thanks for fixing this

**Pull request merged**
